# Generated by Django 3.1.4 on 2021-01-08 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontact',
            name='contact_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatcontact',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
