# Generated by Django 3.1.4 on 2021-02-19 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BookAdvertisement', '0004_auto_20210219_2045'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdScore',
            fields=[
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='advertisement', serialize=False, to='BookAdvertisement.bookad')),
                ('score', models.IntegerField(default=1)),
                ('score_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
