# Generated by Django 3.1.4 on 2021-02-19 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdvertisement', '0004_auto_20210219_2045'),
        ('user_score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adscore',
            name='advertisement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='advertisement', serialize=False, to='BookAdvertisement.bookad'),
        ),
    ]
