# Generated by Django 3.1.4 on 2021-01-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatcontact',
            old_name='last_messages',
            new_name='last_message',
        ),
    ]
