# Generated by Django 3.1.4 on 2021-01-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdvertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookad',
            name='suggested_money',
            field=models.IntegerField(default=0, verbose_name='قیمت پیشنهادی'),
        ),
    ]
