# Generated by Django 3.1.4 on 2021-02-19 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookAdvertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookad',
            name='addresser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DONE', 'Done')], default='PENDING', max_length=255, verbose_name='status'),
        ),
    ]
