# Generated by Django 3.1.4 on 2021-02-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdvertisement', '0002_auto_20210108_1248'),
        ('BookAdvertisement', '0002_auto_20210219_1905'),
    ]

    operations = [
    ]
