# Generated by Django 3.1.4 on 2021-02-19 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookAdvertisement', '0003_merge_20210219_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookad',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='suggested_money',
            field=models.IntegerField(default=0, verbose_name='suggested money'),
        ),
    ]
