# Generated by Django 3.1.4 on 2021-02-19 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookAdvertisement', '0004_auto_20210219_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookad',
            name='addresser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresser', to=settings.AUTH_USER_MODEL),
        ),
    ]
