# Generated by Django 3.1.4 on 2021-01-08 10:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='ad_posters/', verbose_name='تصویر')),
                ('title', models.CharField(max_length=30, verbose_name='نام کتاب')),
                ('author', models.CharField(max_length=30, verbose_name='نام نویسنده')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('sell', models.BooleanField(verbose_name='فروشی')),
                ('suggested_money', models.IntegerField(default=0, verbose_name='suggested money')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255, verbose_name='status')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
