# Generated by Django 3.1.4 on 2020-12-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdvertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookad',
            name='author',
            field=models.CharField(max_length=30, verbose_name='نام نویسنده'),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='description',
            field=models.TextField(max_length=500, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='ad_posters/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='sell',
            field=models.BooleanField(verbose_name='فروشی'),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='title',
            field=models.CharField(max_length=30, verbose_name='نام کتاب'),
        ),
    ]
