# Generated by Django 3.1.3 on 2020-11-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdvertisement', '0002_auto_20201109_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookad',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='ad_posters/'),
        ),
    ]
