# Generated by Django 3.1.4 on 2020-12-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdvertisement', '0005_auto_20201220_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookad',
            name='suggested_money',
            field=models.IntegerField(default=0),
        ),
    ]
