# Generated by Django 3.1.4 on 2020-12-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdvertisement', '0002_auto_20201213_2202'),
        ('BookAdvertisement', '0006_bookad_suggested_money'),
    ]

    operations = [
    ]
