# Generated by Django 3.1.4 on 2020-12-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdvertisement', '0007_merge_20201220_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookad',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255, verbose_name='status'),
        ),
    ]
