# Generated by Django 3.1.4 on 2020-12-23 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdvertisement', '0009_auto_20201222_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookad',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 6, 36, 5, 291878)),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='suggested_money',
            field=models.IntegerField(default=0, verbose_name='suggested money'),
        ),
    ]
