# Generated by Django 3.1.4 on 2020-12-23 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdvertisement', '0010_auto_20201223_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookad',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 6, 37, 2, 583808, tzinfo=utc)),
        ),
    ]
