# Generated by Django 3.1.4 on 2020-12-23 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdvertisement', '0011_auto_20201223_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookad',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
    ]
