# Generated by Django 3.1.4 on 2020-12-23 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdvertisement', '0012_auto_20201223_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookad',
            name='modified_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
    ]
