# Generated by Django 3.1.4 on 2020-12-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdvertisement', '0013_bookad_modified_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookad',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
