# Generated by Django 3.1.4 on 2020-12-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdvertisement', '0014_auto_20201223_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookad',
            name='modified_datetime',
            field=models.DateTimeField(),
        ),
    ]
